### ISSUE TITLE
Save model in pb format

### ISSUE THREAD

**Issue by svazzole** [emadboctorx/yolo-tf2#29]
Hi! Thanks for this amazing project!

I'm wondering if it is possible to save the model in pb format. I'm trying something like this:
```python
from yolo_tf2.core.detector import Detector
from yolo_tf2.utils.common import get_abs_path
import tensorflow as tf
import numpy as np


detector = Detector(
     input_shape=(416, 416, 3),
     model_configuration="yolo_tf2/config/yolo3.cfg",
     classes_file="/path/to/classes.txt",
     score_threshold=0.25,
     iou_threshold=0.25,
     max_boxes=100
 )


weights = "./models/model.tf"
_, _ = detector.create_models(reverse_v4=True)
detector.load_weights(get_abs_path(weights, verify=True))

inference_model = detector.inference_model
image = np.random.random((416, 416, 3))
print(inference_model.predict(image[np.newaxis, ...]))

tf.saved_model.save(inference_model, "yolo_model")
```
but I'm getting this error:
```
TypeError: cannot pickle '_thread.RLock' object
```
What I'm trying to do is to save the inference model as a "standalone" pb model. Do you think that it's possible?
Best!

**Comment by emadboctorx** [comment]
Thank you for your interest in this project, please provide a full error log, system information, package versions, python version, tf version ... and let me know where this `"./models/model.tf"` comes from, is it a training checkpoint result? are these weights found online? else? I tried something similar to what you included on my macbook and I got a different error so, the more context, the better.

**Comment by svazzole** [comment]
Thanks for your response!

1. The file `"./models/model.tf"` is the result of a training of a yolov3 model. 
2. I tried your code but it does not run, giving the following error:
```
2021-06-04 09:29:53.691331: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
Traceback (most recent call last):
  File "save_keras_model.py", line 5, in <module>
    model = tf.keras.models.load_model('./models/model.tf')
  File "C:\Users\User\workspace\yolo-tf2\venv\lib\site-packages\tensorflow\python\keras\saving\save.py", line 211, in load_model
    loader_impl.parse_saved_model(filepath)
  File "C:\Users\User\workspace\yolo-tf2\venv\lib\site-packages\tensorflow\python\saved_model\loader_impl.py", line 111, in parse_saved_model
    raise IOError("SavedModel file does not exist at: %s/{%s|%s}" %
OSError: SavedModel file does not exist at: ./models/model.tf/{saved_model.pbtxt|saved_model.pb}
```

## System Information
OS: Win 10 / Ubuntu 18.04 (Kernel 4.15.0-140-generic)
Python: 3.8.5 (Win 10) / 3.8.10 (Ubuntu 18.04)

In the attachments you can find the packages versions, the logs.
Thanks!

[logs.txt](https://github.com/emadboctorx/yolo-tf2/files/6596604/logs.txt)
[pip_list_ubuntu.txt](https://github.com/emadboctorx/yolo-tf2/files/6596605/pip_list_ubuntu.txt)
[pip_list_win.txt](https://github.com/emadboctorx/yolo-tf2/files/6596606/pip_list_win.txt)

**Comment by emadboctorx** [comment]
I was able to save the model to .pb format after making a few changes which I pushed to [pb_support](https://github.com/emadboctorx/yolo-tf2/tree/pb_support) branch. Please check this [notebook](https://colab.research.google.com/drive/1C9mMHwMsJiPYNkOnMSnQcTcm8YcbRuga?usp=sharing) which has the steps below:

    git clone https://github.com/emadboctorx/yolo-tf2/
    cd yolo-tf2
    git checkout pb_support
    pip install .

Then:

    Python 3.8.10 (default, May  5 2021, 03:01:07) 
    [GCC 7.5.0] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> from yolo_tf2.core.models import BaseModel
    2021-06-04 14:06:44.931941: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
    >>> base_model = BaseModel(     (416, 416, 3), 'yolo_tf2/config/yolo3.cfg' )
    >>> _, inference_model = base_model.create_models()
    2021-06-04 14:06:59.438495: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcuda.so.1
    2021-06-04 14:06:59.493199: E tensorflow/stream_executor/cuda/cuda_driver.cc:328] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
    2021-06-04 14:06:59.493269: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (ce8492259283): /proc/driver/nvidia/version does not exist
    2021-06-04 14:06:59.493614: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
    To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
    2021-06-04 14:07:01,420 yolo_tf2.utils.common.create_models +457: INFO     [2998] Training and inference models created
    2021-06-04 14:07:01,420 yolo_tf2.utils.common.wrapper +64: INFO     [2998] create_models execution time: 2.0139396530000795 seconds
    >>> inference_model.save('/content/yolo_model')
    WARNING:tensorflow:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
    2021-06-04 14:07:29.328989: W tensorflow/python/util/util.cc:348] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
    /usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/utils/generic_utils.py:494: CustomMaskWarning: Custom mask layers require a config and must override get_config. When loading, the custom mask layer must be passed to the custom_objects argument.
      warnings.warn('Custom mask layers require a config and must override '
    INFO:tensorflow:Assets written to: /content/yolo_model/assets
    >>> 
    KeyboardInterrupt

Please let me know if this solves the problem.

**Comment by svazzole** [comment]
It works!
To load it one must use
```python
tf.keras.models.load_model("/path/to/saved/model/folder")
```
Thanks a lot!

**Comment by emadboctorx** [comment]
Glad to help, I'll close the issue, feel free to re-open if you encounter further problems.
